//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\annar\Desktop\Kompilator\Kom\Gramatyka.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GramatykaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IGramatykaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] GramatykaParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] GramatykaParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>print</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] GramatykaParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assign</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] GramatykaParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprAssign</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAssign([NotNull] GramatykaParser.ExprAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vectDeclaration</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectDeclaration([NotNull] GramatykaParser.VectDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vectAssign</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectAssign([NotNull] GramatykaParser.VectAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vectExprAssign</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectExprAssign([NotNull] GramatykaParser.VectExprAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vectAllAssign</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectAllAssign([NotNull] GramatykaParser.VectAllAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readInt</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadInt([NotNull] GramatykaParser.ReadIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>readReal</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadReal([NotNull] GramatykaParser.ReadRealContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] GramatykaParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] GramatykaParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>while</c>
	/// labeled alternative in <see cref="GramatykaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] GramatykaParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] GramatykaParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.vect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVect([NotNull] GramatykaParser.VectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.numbers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumbers([NotNull] GramatykaParser.NumbersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] GramatykaParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExpr([NotNull] GramatykaParser.ArithmeticExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] GramatykaParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] GramatykaParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] GramatykaParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.equal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqual([NotNull] GramatykaParser.EqualContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.blockIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockIf([NotNull] GramatykaParser.BlockIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GramatykaParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] GramatykaParser.ConditionContext context);
}
